[package]
name = "rust-video-captioning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Add dependencies here, e.g.,
# ffmpeg = "0.4"
# some-captioning-crate = "0.1"